language: r
sudo: false
cache: packages
latex: false

r-github-packages:
  - jimhester/covr
  - dmenne/breathtestcore

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::coveralls()'

