language: r
r: devel
sudo: FALSE
cache: packages

warnings_are_errors: TRUE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

r_github_packages:
  - jimhester/covr

script:
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check breathteststan*tar.gz

after_script:
  - tar -ztvf breathteststan_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - travis_wait 40 Rscript -e 'covr::coveralls("src/init.cpp")'

