language: r
sudo: false
cache: packages
dist: trusty
latex: false


r-github-packages:
  - jimhester/covr
  - dmenne/breathtestcore

after_success:
  - tar -C .. -xf $PKG_TARBALL
  - Rscript -e 'covr::coveralls(line_exclusions= c("/src/include/models.hpp", "src/*.cpp", "R/zzz.R"))'
